#!/bin/bash

# CD Tool Quick Start Script
# Complete setup for development and deployment

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Configuration
CD_VERSION="2.0.0"
SETUP_MODE=""
SERVER_PORT="8080"
API_KEY=""
DOCKER_MODE=false
DEV_MODE=false

# Print functions
print_header() {
    echo -e "${CYAN}${BOLD}================================${NC}"
    echo -e "${CYAN}${BOLD}    CD Tool Quick Start v${CD_VERSION}${NC}"
    echo -e "${CYAN}${BOLD}================================${NC}"
    echo
}

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_step() {
    echo -e "${CYAN}${BOLD}=== $1 ===${NC}"
}

# Help function
show_help() {
    echo "CD Tool Quick Start Script"
    echo
    echo "This script sets up the complete CD Tool environment for development or production."
    echo
    echo "Usage: $0 [MODE] [OPTIONS]"
    echo
    echo "Modes:"
    echo "  dev         Development setup (local build)"
    echo "  docker      Docker container deployment"
    echo "  production  Production-ready setup"
    echo "  test        Test environment setup"
    echo
    echo "Options:"
    echo "  -h, --help          Show this help message"
    echo "  -p, --port PORT     Set server port (default: 8080)"
    echo "  -k, --key KEY       Set API key (generated if not provided)"
    echo "  --no-build          Skip building binaries"
    echo "  --no-test           Skip running tests"
    echo "  --clean             Clean previous setup"
    echo
    echo "Examples:"
    echo "  $0 dev                    # Development setup"
    echo "  $0 docker --port 9000     # Docker setup on port 9000"
    echo "  $0 production --clean     # Clean production setup"
    echo "  $0 test --no-build        # Test without building"
    echo
    echo "Environment Variables:"
    echo "  CD_API_KEY              Pre-set API key"
    echo "  CD_PORT                 Pre-set port"
    echo "  CD_SKIP_TESTS           Skip tests (true/false)"
    echo
}

# Check prerequisites
check_prerequisites() {
    print_step "Checking Prerequisites"

    # Check Go
    if ! command -v go &> /dev/null; then
        print_error "Go is not installed. Please install Go 1.21 or later."
        echo "  macOS: brew install go"
        echo "  Linux: sudo apt-get install golang-go"
        echo "  Windows: Download from https://golang.org/dl/"
        exit 1
    fi

    local go_version=$(go version | grep -o 'go[0-9]\+\.[0-9]\+' | sed 's/go//')
    print_status "Go version: $go_version"

    # Check Git
    if ! command -v git &> /dev/null; then
        print_warning "Git is not installed. Some features may not work."
    else
        print_status "Git: $(git --version)"
    fi

    # Check Docker (if docker mode)
    if [ "$DOCKER_MODE" = true ]; then
        if ! command -v docker &> /dev/null; then
            print_error "Docker is not installed but required for Docker mode."
            echo "  macOS: brew install --cask docker"
            echo "  Linux: sudo apt-get install docker.io"
            echo "  Windows: Download from https://docker.com"
            exit 1
        fi

        if ! docker info &> /dev/null; then
            print_error "Docker daemon is not running."
            exit 1
        fi

        print_status "Docker: $(docker --version)"
    fi

    print_success "Prerequisites check completed"
}

# Generate API key
generate_api_key() {
    if [ -z "$API_KEY" ]; then
        if command -v openssl &> /dev/null; then
            API_KEY=$(openssl rand -hex 32)
        else
            # Fallback random generation
            API_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)
        fi
        print_status "Generated API key: $API_KEY"
    else
        print_status "Using provided API key"
    fi
}

# Create configuration
create_config() {
    print_step "Creating Configuration"

    generate_api_key

    cat > config.toml << EOF
# CD Tool Server Configuration
# Generated by quick-start.sh on $(date)

# Server listen address
listen_addr = ':$SERVER_PORT'

# API keys for authentication
api_keys = [
    '$API_KEY'
]

# Optional settings
log_level = 'info'
max_deployments = 5

# Environment: $SETUP_MODE
EOF

    print_success "Configuration created: config.toml"
    print_warning "Save your API key: $API_KEY"
}

# Clean previous setup
clean_setup() {
    print_step "Cleaning Previous Setup"

    # Remove binaries
    rm -rf bin/
    print_status "Removed binaries"

    # Remove Docker containers and images (if docker mode)
    if [ "$DOCKER_MODE" = true ]; then
        docker rm -f cd-server 2>/dev/null || true
        docker rmi cd-tool:latest 2>/dev/null || true
        print_status "Removed Docker containers and images"
    fi

    # Remove temporary files
    rm -rf /tmp/cd-*
    print_status "Removed temporary files"

    print_success "Cleanup completed"
}

# Build binaries
build_binaries() {
    print_step "Building Binaries"

    # Create bin directory
    mkdir -p bin

    # Build server
    print_status "Building CD server..."
    go build -o bin/cd-server ./cmd/server

    # Build CLI
    print_status "Building CD CLI..."
    go build -o bin/cd-cli ./cmd/cli

    print_success "Binaries built successfully"
}

# Run tests
run_tests() {
    print_step "Running Tests"

    if [ "${CD_SKIP_TESTS:-false}" = "true" ]; then
        print_warning "Skipping tests (CD_SKIP_TESTS=true)"
        return
    fi

    print_status "Running test suite..."
    if make test; then
        print_success "All tests passed"
    else
        print_warning "Some tests failed, but continuing setup"
    fi
}

# Docker setup
setup_docker() {
    print_step "Setting up Docker Environment"

    # Run docker setup script
    if [ -f "./docker-setup.sh" ]; then
        print_status "Running Docker setup script..."
        ./docker-setup.sh --port "$SERVER_PORT"
    else
        print_error "docker-setup.sh not found"
        exit 1
    fi

    print_success "Docker setup completed"
}

# Start local server
start_local_server() {
    print_step "Starting Local Server"

    # Check if port is available
    if lsof -Pi :$SERVER_PORT -sTCP:LISTEN -t >/dev/null 2>&1; then
        print_warning "Port $SERVER_PORT is already in use"
        print_status "Trying to stop existing server..."
        pkill cd-server || true
        sleep 2
    fi

    print_status "Starting CD server on port $SERVER_PORT..."
    echo "  Server will start in background"
    echo "  View logs: tail -f server.log"
    echo "  Stop server: pkill cd-server"

    # Start server in background
    nohup ./bin/cd-server > server.log 2>&1 &
    local server_pid=$!

    # Wait for server to start
    sleep 3

    if kill -0 $server_pid 2>/dev/null; then
        print_success "Server started successfully (PID: $server_pid)"
        echo $server_pid > .server.pid
    else
        print_error "Server failed to start. Check server.log for details."
        exit 1
    fi
}

# Test deployment
test_deployment() {
    print_step "Testing Deployment"

    print_status "Testing CLI connection..."

    # Test CLI help
    if ./bin/cd-cli -help > /dev/null 2>&1; then
        print_success "CLI is working"
    else
        print_error "CLI test failed"
        return 1
    fi

    # Test Docker diagnostics
    print_status "Running Docker diagnostics..."
    ./bin/cd-cli -diagnose

    # Test server connection (if not docker mode)
    if [ "$DOCKER_MODE" != true ]; then
        print_status "Testing server connection..."
        sleep 2

        # Try to connect to server
        if timeout 10 ./bin/cd-cli -server=localhost:$SERVER_PORT -key="$API_KEY" -git=https://github.com/example/test.git 2>/dev/null; then
            print_success "Server connection test passed"
        else
            print_warning "Server connection test failed (expected for invalid git URL)"
        fi
    fi

    print_success "Testing completed"
}

# Setup development environment
setup_development() {
    print_step "Setting up Development Environment"

    # Install development tools
    print_status "Installing development dependencies..."
    go mod download
    go mod tidy

    # Create example files
    if [ ! -f ".env.example" ]; then
        print_status "Creating example environment file..."
        # File already exists from previous setup
    fi

    # Create development scripts
    cat > dev.sh << 'EOF'
#!/bin/bash
# Development helper script

case "$1" in
    "server")
        echo "Starting development server..."
        go run cmd/server/main.go
        ;;
    "cli")
        shift
        echo "Running CLI with args: $@"
        go run cmd/cli/main.go "$@"
        ;;
    "test")
        echo "Running tests..."
        make test
        ;;
    "build")
        echo "Building binaries..."
        make build
        ;;
    *)
        echo "Usage: $0 {server|cli|test|build}"
        echo "Examples:"
        echo "  $0 server                    # Start server"
        echo "  $0 cli -diagnose             # Run CLI diagnostics"
        echo "  $0 test                      # Run tests"
        echo "  $0 build                     # Build binaries"
        ;;
esac
EOF
    chmod +x dev.sh

    print_success "Development environment ready"

    echo
    echo -e "${YELLOW}Development Commands:${NC}"
    echo "  ./dev.sh server              # Start development server"
    echo "  ./dev.sh cli -help           # Use CLI tool"
    echo "  ./dev.sh test                # Run tests"
    echo "  ./dev.sh build               # Build binaries"
}

# Display final information
show_final_info() {
    echo
    print_step "Setup Complete!"

    echo -e "${YELLOW}Configuration:${NC}"
    echo "  Mode: $SETUP_MODE"
    echo "  Port: $SERVER_PORT"
    echo "  API Key: $API_KEY"
    echo "  Config File: config.toml"
    echo

    if [ "$DOCKER_MODE" = true ]; then
        echo -e "${YELLOW}Docker Commands:${NC}"
        echo "  docker logs -f cd-server         # View logs"
        echo "  docker stop cd-server            # Stop server"
        echo "  docker start cd-server           # Start server"
        echo "  ./docker-setup.sh --remove      # Remove container"
    else
        echo -e "${YELLOW}Server Management:${NC}"
        echo "  tail -f server.log               # View logs"
        echo "  pkill cd-server                  # Stop server"
        echo "  ./bin/cd-server                  # Start server"
    fi

    echo
    echo -e "${YELLOW}Usage Examples:${NC}"
    echo "  # Test deployment"
    echo "  ./bin/cd-cli -server=localhost:$SERVER_PORT -key=\"$API_KEY\" \\"
    echo "              -git=https://github.com/user/repo.git"
    echo
    echo "  # With environment variables"
    echo "  ./bin/cd-cli -server=localhost:$SERVER_PORT -key=\"$API_KEY\" \\"
    echo "              -git=https://github.com/user/repo.git \\"
    echo "              -env-vars=\"API_KEY=value,DEBUG=true\""
    echo

    echo -e "${YELLOW}Next Steps:${NC}"
    echo "  1. Edit config.toml to customize settings"
    echo "  2. Add your repository secrets to GitHub"
    echo "  3. Copy workflow templates to your repositories"
    echo "  4. Start deploying!"
    echo

    echo -e "${YELLOW}Documentation:${NC}"
    echo "  README.md                        # Main documentation"
    echo "  docs/ENVIRONMENT_VARIABLES.md    # Environment variables guide"
    echo "  docs/DOCKER_DEPLOYMENT.md        # Docker deployment guide"
    echo "  examples/deploy-with-env-vars.yml # Example workflow"
    echo

    print_success "CD Tool is ready to use!"
}

# Parse command line arguments
parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            dev|development)
                SETUP_MODE="development"
                DEV_MODE=true
                shift
                ;;
            docker)
                SETUP_MODE="docker"
                DOCKER_MODE=true
                shift
                ;;
            production|prod)
                SETUP_MODE="production"
                shift
                ;;
            test)
                SETUP_MODE="test"
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            -p|--port)
                SERVER_PORT="$2"
                shift 2
                ;;
            -k|--key)
                API_KEY="$2"
                shift 2
                ;;
            --no-build)
                NO_BUILD=true
                shift
                ;;
            --no-test)
                CD_SKIP_TESTS=true
                shift
                ;;
            --clean)
                CLEAN=true
                shift
                ;;
            *)
                print_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # Default mode
    if [ -z "$SETUP_MODE" ]; then
        SETUP_MODE="development"
        DEV_MODE=true
    fi

    # Use environment variables if set
    SERVER_PORT="${CD_PORT:-$SERVER_PORT}"
    API_KEY="${CD_API_KEY:-$API_KEY}"
}

# Main execution flow
main() {
    print_header

    parse_arguments "$@"

    print_status "Setup mode: $SETUP_MODE"
    print_status "Server port: $SERVER_PORT"

    # Clean if requested
    if [ "$CLEAN" = true ]; then
        clean_setup
    fi

    # Check prerequisites
    check_prerequisites

    # Create configuration
    create_config

    # Build or setup based on mode
    case "$SETUP_MODE" in
        "development")
            if [ "$NO_BUILD" != true ]; then
                build_binaries
                run_tests
            fi
            setup_development
            start_local_server
            test_deployment
            ;;
        "docker")
            if [ "$NO_BUILD" != true ]; then
                run_tests
            fi
            setup_docker
            test_deployment
            ;;
        "production")
            if [ "$NO_BUILD" != true ]; then
                build_binaries
                run_tests
            fi
            start_local_server
            test_deployment
            ;;
        "test")
            if [ "$NO_BUILD" != true ]; then
                build_binaries
            fi
            run_tests
            test_deployment
            ;;
    esac

    # Show final information
    show_final_info
}

# Run main function with all arguments
main "$@"
